export * from './i-crud-auto-module-options.interface';
export * from './i-crud-module-options.interface';
export * from './i-dictionary.interface';
export * from './i-dto-recipe.interface';
export * from './i-endpoints-recipe.interface';
export * from './i-entity-recipe.interface';
export * from './i-paginated-result.interface';
export * from './i-pagination.interface';
export * from './i-recipe-metadata.interface';
